language: python
python:
  - "2.7"
install:
  - pip install pep8 --use-mirrors
sudo: false
script:
  - pep8
  - python -m doctest sparkprs/utils.py
  - npm install .
  - npm install -g grunt-cli
  - grunt lint
